### ISSUE TITLE
Не хватает файлов для компиляции Ангем РК1

### ISSUE THREAD

**Issue by Neizvestnyj** [pluttan/BMSTU-1#1]
Необходимо добавить:

1. bw2.png
2. image1.png
3. image2.png
4. image3.png
5. image4.png
6. image5.png
7. img/3.png
8. img/4.png
9. img/5.png

**Comment by pluttan** [comment]
Файлы эти имеются, но они лежат в другой папке (conf/img) bw2 это лого, в обозримом будущем оно будет выложено на сервер и будет скачиваться автоматически, так что советуюсь обзавестись Shell-excape)
